# Default Tmux Configuration

# Set prefix to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Use vi-mode for copy mode
set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse mode
set -g mouse on

# More intuitive keybindings for splitting panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Keybindings for switching panes with vim-like keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with vim-like keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Reload config file with r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind-key -r f run-shell "tmux neww ~/.config/tmux/tmux-sessionizer.sh"

# Visual notifications
set -g visual-activity on
set-window-option -g monitor-activity on

# 256 color support
set -g default-terminal "screen-256color"

# TokyoNight theme
source-file "~/.config/tmux/tokyonight_night.tmux" 

